/*******************************************************************************
 * Copyright (c) 2025 Tlcsdm. All rights reserved.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution,
 * and is available at https://www.eclipse.org/legal/epl-v20.html
 ******************************************************************************/
package com.tlcsdm.eclipse.gefemf.demo.preferences;

/**
 * Constants for the LVGL UI Editor preferences.
 */
public class LvglPreferenceConstants {

	/**
	 * Preference key for the license header text.
	 */
	public static final String P_LICENSE_HEADER = "licenseHeader";

	/**
	 * Default license header template.
	 */
	public static final String DEFAULT_LICENSE_HEADER = 
			"/*\n" +
			" * Auto-generated LVGL UI code\n" +
			" * Generated by LVGL UI Editor\n" +
			" */";

	private LvglPreferenceConstants() {
		// Constants class
	}
}
